# Generated by Django 3.2.13 on 2023-08-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchName', models.CharField(max_length=255, unique=True)),
                ('BranchCode', models.IntegerField(unique=True)),
                ('Contact', models.CharField(max_length=255)),
                ('IFSCCode', models.CharField(max_length=11, unique=True)),
                ('MICRCODE', models.IntegerField(unique=True)),
                ('District', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=300)),
                ('PinCode', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': "Branch's Data",
            },
        ),
        migrations.CreateModel(
            name='LinksMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkType', models.CharField(choices=[('1', 'Abhyudaya'), ('2', 'NPCI'), ('3', 'Internet')], default='1', max_length=50)),
                ('LinkName', models.CharField(max_length=50)),
                ('Link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Links',
                'verbose_name_plural': 'Links Manager',
                'unique_together': {('LinkType', 'LinkName')},
            },
        ),
        migrations.CreateModel(
            name='Passw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationName', models.CharField(choices=[('1', 'NPCI-UPI'), ('2', 'NPCI-IMPS'), ('3', 'NPCI-NFS'), ('4', 'NPCI-AEPS'), ('5', 'NPCI-RUPAY'), ('6', 'CONCERTO'), ('7', 'EXCHANGE'), ('8', 'OTHER')], default='1', max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password',
                'verbose_name_plural': 'Password Manager',
                'unique_together': {('ApplicationName', 'UserName')},
            },
        ),
    ]
