# Generated by Django 3.2.13 on 2023-04-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchName', models.CharField(max_length=255)),
                ('BranchCode', models.IntegerField(max_length=3)),
                ('Contact', models.CharField(max_length=255)),
                ('IFSCCode', models.CharField(max_length=11)),
                ('MICRCODE', models.IntegerField(max_length=9)),
                ('District', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=300)),
                ('PinCode', models.IntegerField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
