# Generated by Django 3.2.13 on 2023-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchFinder', '0002_auto_20230506_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passw',
            name='ApplicationName',
            field=models.CharField(choices=[('1', 'NPCI-UPI'), ('2', 'NPCI-IMPS'), ('3', 'NPCI-NFS'), ('4', 'NPCI-AEPS'), ('5', 'NPCI-RUPAY'), ('6', 'CONCERTO'), ('7', 'EXCHANGE'), ('8', 'OTHER')], default='1', max_length=50),
        ),
    ]
