# Generated by Django 3.2.13 on 2023-05-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BranchFinder', '0003_auto_20230506_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_at',
        ),
    ]
