# Generated by Django 3.2.13 on 2023-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchFinder', '0005_auto_20230506_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=-2008),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.0011409273457466229),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
