# Generated by Django 3.2.13 on 2023-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchFinder', '0006_auto_20230506_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': "Branch's Data"},
        ),
        migrations.AlterModelOptions(
            name='passw',
            options={'verbose_name': 'Password', 'verbose_name_plural': 'Password Manager'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='branch',
            name='BranchCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BranchName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='IFSCCode',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='MICRCODE',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='passw',
            unique_together={('ApplicationName', 'UserName')},
        ),
        migrations.RemoveField(
            model_name='passw',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passw',
            name='updated_at',
        ),
    ]
